FROM oraclelinux:6
MAINTAINER Justin Paul <justin.paul@oracle.com>

ENV _SCRATCH /tmp/scratch
ENV ORA_HOME /u01/app/oracle
ENV JDK_HOME ${ORA_HOME}/product/jdk
ENV FMW_HOME ${ORA_HOME}/product/fmw
ENV ADM_HOME ${ORA_HOME}/admin

COPY jdk ${_SCRATCH}/jdk/
COPY wls ${_SCRATCH}/wls/
COPY rcu ${_SCRATCH}/rcu/
COPY wcc ${_SCRATCH}/wcc/
COPY domain ${_SCRATCH}/domain/
COPY scripts ${_SCRATCH}/scripts/

RUN yum update -y -q && \
	yum install -y -q binutils compat-libcap1 compat-libstdc++-33 \
	compat-libstdc++-33.i686 gcc gcc-c++ glibc glibc-devel glibc-devel.i686 \
	libaio libaio-devel libgcc libgcc.i686 libstdc++ libstdc++.i686 \
	libstdc++-devel libXext libXtst libXi openmotif openmotif22 redhat-lsb \
	sysstat zlib zlib.i686 libX11 libX11.i686 unzip xorg-x11-utils xorg-x11-xauth && \
	groupadd -g 1000 oinstall && \
	useradd -u 1000 -g 1000 -m oracle && \
	mkdir -p ${ORA_HOME} && \
	chown -R oracle:oinstall ${_SCRATCH} && \
	chown -R oracle:oinstall ${ORA_HOME}

USER oracle

RUN unzip ${_SCRATCH}/jdk/p21984104_17091_Linux-x86-64.zip -d ${_SCRATCH}/jdk && \
	mkdir -p ${JDK_HOME} && \
	tar xzf ${_SCRATCH}/jdk/jdk-7u91-linux-x64.tar.gz -C ${JDK_HOME} --strip-components=1 && \
	mkdir -p ${FMW_HOME} && \
	${JDK_HOME}/bin/java -jar ${_SCRATCH}/wls/wls1036_generic.jar -mode=silent \
	-silent_xml=${_SCRATCH}/wls/silent.xml && \
	unzip ${_SCRATCH}/rcu/ofm_rcu_linux_11.1.1.9.0_64_disk1_1of1.zip -d ${FMW_HOME} && \
	echo "inventory_loc=${FMW_HOME}/oraInventory" > ${_SCRATCH}/oraInst.loc && \
	echo "inst_group=oinstall" >> ${_SCRATCH}/oraInst.loc && \
	unzip ${_SCRATCH}/wcc/ofm_wcc_generic_11.1.1.9.0_disk1_1of2.zip -d ${_SCRATCH}/wcc && \
	unzip ${_SCRATCH}/wcc/ofm_wcc_generic_11.1.1.9.0_disk1_2of2.zip -d ${_SCRATCH}/wcc && \
	${_SCRATCH}/wcc/Disk1/runInstaller -silent -invPtrLoc ${_SCRATCH}/oraInst.loc \
	-responseFile ${_SCRATCH}/wcc/Disk1/stage/Response/sampleResponse_wls.rsp -jreLoc ${JDK_HOME} \
	-waitforcompletion -force -novalidation MIDDLEWARE_HOME=${FMW_HOME} \
	ORACLE_HOME=${FMW_HOME}/Oracle_ECM1 && \
	mkdir -p ${ADM_HOME}/tools/templates && \
	mkdir -p ${ADM_HOME}/tools/scripts && \
	cp ${_SCRATCH}/domain/* ${ADM_HOME}/tools/templates && \
	cp -r ${_SCRATCH}/scripts/* ${ADM_HOME}/tools/scripts

RUN mkdir -p ${FMW_HOME}/utils/bsu/cache_dir && \
	unzip ${_SCRATCH}/wls/p20780171_1036_Generic.zip -d ${FMW_HOME}/utils/bsu/cache_dir && \
	cd ${FMW_HOME}/utils/bsu && \
	sed -i 's/-Xmx512m/-Xmx1024m/g' ${FMW_HOME}/utils/bsu/bsu.sh && \
	${FMW_HOME}/utils/bsu/bsu.sh -prod_dir=${FMW_HOME}/wlserver_10.3 -patchlist=EJUW -verbose -install && \
	cd && \
	unzip ${_SCRATCH}/wcc/p22060967_111190_Generic.zip && \
	unzip ${_SCRATCH}/wcc/p22249978_111190_Generic.zip -d ${_SCRATCH}/wcc && \
	${FMW_HOME}/Oracle_ECM1/OPatch/opatch apply -silent ${_SCRATCH}/wcc/22060967 && \
	${FMW_HOME}/Oracle_ECM1/OPatch/opatch apply -silent ${_SCRATCH}/wcc/ECM_22249978

RUN rm -rf ${_SCRATCH}

CMD /bin/bash
